name: pintar_akademik
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  camera: ^0.11.0+2
  geocoding: ^3.0.0
  intl: ^0.19.0
  lottie: ^3.0.0
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  flutter_youtube_view: ^2.0.4
  youtube_player_flutter: ^9.0.3
  crypto: ^3.0.0
  fl_chart: ^0.69.0
  syncfusion_flutter_calendar: ^27.1.57
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  flutter_countdown_timer: ^4.1.0
  countdown_progress_indicator: ^0.1.3
  flutter_js: ^0.8.1
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  permission_handler: ^11.3.1
  pdfx: ^2.8.0
  pdf_render: ^1.4.12
  geolocator: ^13.0.2
  google_ml_kit: ^0.19.0
  flutter_calendar_carousel: ^2.4.4
  file_picker: ^5.0.1
  image_picker: ^1.1.2
  flutter_form_builder: ^9.6.0
  form_builder_validators: ^11.1.1
  jitsi_meet_flutter_sdk: ^10.3.0
  flutter_image_compress: ^2.3.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/raw/
     - assets/illustration/